CREATE DATABASE QUANLYHOCVIEN
GO

USE QUANLYHOCVIEN
GO

CREATE TABLE CHINHANH (
	MACN VARCHAR(5),
	DIACHI NVARCHAR(50),
	DIENTICH INT,
	CONSTRAINT PK_MACN PRIMARY KEY(MACN)
)
GO

CREATE TABLE NGANH (
	MANGANH VARCHAR(10),
	TENNGANH NVARCHAR(50),
	CONSTRAINT PK_MANGANH PRIMARY KEY(MANGANH)
)
GO

CREATE TABLE GIANGVIEN (
	MAGV VARCHAR(6),
	HOTEN NVARCHAR(50),
	EMAIL VARCHAR(50),
	HOCVI NVARCHAR(20),
	CONSTRAINT PK_MAGV PRIMARY KEY(MAGV)
)
GO

CREATE TABLE LOP (
	MALOP VARCHAR(8),
	MAGV VARCHAR(6),
	MACN VARCHAR(5),
	MANGANH VARCHAR(10),
	TENLOP NVARCHAR(50),
	SOLUONGSV INT,
	CONSTRAINT PK_MALOP PRIMARY KEY(MALOP),
	CONSTRAINT FK_MAGV_LOP_GV FOREIGN KEY(MAGV) REFERENCES GIANGVIEN(MAGV),
	CONSTRAINT FK_MACN_LOP_CN FOREIGN KEY(MACN) REFERENCES CHINHANH(MACN),
	CONSTRAINT FK_MANGANH_LOP_NGANH FOREIGN KEY(MANGANH) REFERENCES NGANH(MANGANH)
)
GO

CREATE TABLE SINHVIEN (
	MASV VARCHAR(8),
	MALOP VARCHAR(8),
	HOTEN NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(5),
	QUEQUAN NVARCHAR(50),
	CONSTRAINT PK_MASV PRIMARY KEY(MASV),
	CONSTRAINT FK_MALOP_SV_LOP FOREIGN KEY(MALOP) REFERENCES LOP(MALOP)
)
GO

CREATE TABLE MONHOC (
	MAMON VARCHAR(5),
	TENMON NVARCHAR(50),
	SOTIET INT,
	CONSTRAINT PK_MAMON PRIMARY KEY(MAMON)
)
GO

CREATE TABLE KETQUA (
	MASV VARCHAR(8),
	MAMON VARCHAR(5),
	DIEMSO FLOAT,
	CONSTRAINT FK_MASV_KQ_SV FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV),
	CONSTRAINT FK_MAMON_KQ_MH FOREIGN KEY(MAMON) REFERENCES MONHOC(MAMON),
	CONSTRAINT PK_MASV_MAMON PRIMARY KEY(MASV, MAMON)
)
GO

CREATE TABLE KHOAHOC (
	MAMON VARCHAR(5),
	MAKH VARCHAR(5),
	MAGV VARCHAR(6),
	TKB VARCHAR(5),
	CONSTRAINT PK_MAMON_MAKH PRIMARY KEY(MAMON, MAKH),
	CONSTRAINT FK_MAGV_KH_GV FOREIGN KEY(MAGV) REFERENCES GIANGVIEN(MAGV),
	CONSTRAINT FK_MAMON_KH_MH FOREIGN KEY(MAMON) REFERENCES MONHOC(MAMON)
)
GO

CREATE TABLE NHANVIEN (
	MANV VARCHAR(5),
	MACN VARCHAR(5),
	HOTEN NVARCHAR(50),
	SDT VARCHAR(10),
	CONSTRAINT PK_MANV PRIMARY KEY(MANV),
	CONSTRAINT FK_MACN_NV_CN FOREIGN KEY (MACN) REFERENCES CHINHANH(MACN)
)
GO

CREATE TABLE KETOAN (
	MANVKT VARCHAR(5),
	MACN VARCHAR(5),
	HOTEN NVARCHAR(50),
	SDT VARCHAR(10),
	BANGCAP NVARCHAR(50),
	CHUNGCHITH NVARCHAR(10),
	CONSTRAINT PK_MANVKT PRIMARY KEY(MANVKT),
	CONSTRAINT FK_MANVKT_KT_NV FOREIGN KEY(MANVKT) REFERENCES NHANVIEN(MANV),
	CONSTRAINT FK_MACN_KT_CN FOREIGN KEY(MACN) REFERENCES CHINHANH(MACN)	
)
GO

CREATE TABLE NHANVIENTUVAN (
	MANVTV VARCHAR(5),
	MACN VARCHAR(5),
	HOTEN NVARCHAR(50),
	SDT VARCHAR(10),
	GPA FLOAT,
	KINHNGHIEM INT,
	CONSTRAINT PK_MANVTV PRIMARY KEY(MANVTV),
	CONSTRAINT FK_MANVTV_NVTV_NV FOREIGN KEY(MANVTV) REFERENCES NHANVIEN(MANV),
	CONSTRAINT FK_MACN_NVTV FOREIGN KEY(MACN) REFERENCES CHINHANH(MACN)
)
GO

-- Tao ma giang vien tu dong
CREATE FUNCTION TAOMAGV (@HOCVI NVARCHAR(20))
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @KIHIEUHV VARCHAR(3)
	SET @KIHIEUHV = CASE 
						WHEN @HOCVI = N'Thạc sĩ' THEN 'THS'
						WHEN @HOCVI = N'Tiến sĩ' THEN 'TS'
						WHEN @HOCVI = N'Kỹ sư' THEN 'KS'
						WHEN @HOCVI = N'Cử nhân' THEN 'CN'
					END
	
	IF NOT EXISTS (SELECT * FROM GIANGVIEN WHERE HOCVI = @HOCVI)
		RETURN @KIHIEUHV + '000'

	ELSE
		BEGIN
			DECLARE @MAGVGANDAY VARCHAR(5), @STTMOI INT, @MAGVMOI VARCHAR(5)
			SET @MAGVGANDAY = (SELECT TOP 1 MAGV FROM GIANGVIEN WHERE HOCVI = @HOCVI ORDER BY MAGV DESC)
			SET @STTMOI = CAST(RIGHT(@MAGVGANDAY, 3) AS INT) + 1
			IF @STTMOI < 10
				SET @MAGVMOI = @KIHIEUHV + '00' + CAST(@STTMOI AS VARCHAR(1))
			ELSE IF @STTMOI < 100
				SET @MAGVMOI = @KIHIEUHV + '0' + CAST(@STTMOI AS VARCHAR(2))
			ELSE 
				SET @MAGVMOI = @KIHIEUHV + CAST(@STTMOI AS VARCHAR(3))
		END
	RETURN @MAGVMOI
END
GO

CREATE PROCEDURE THEMGV @HOTEN NVARCHAR(50), @EMAIL VARCHAR(50), @HOCVI NVARCHAR(20)
AS
	DECLARE @MAGVTUDONG VARCHAR(6)
	SET @MAGVTUDONG = DBO.TAOMAGV(@HOCVI)
	INSERT INTO GIANGVIEN VALUES(@MAGVTUDONG, @HOTEN, @EMAIL, @HOCVI)
GO

EXEC THEMGV N'Trần Đình Tú', 'trandinhtu@gmail.com', N'Tiến sĩ'
EXEC THEMGV N'Lương Quốc Đại', 'luongquocdai@gmail.com', N'Tiến sĩ'
EXEC THEMGV N'Dung Cẩm Quang', 'dungcamquang@gmail.com', N'Tiến sĩ'
EXEC THEMGV N'Dương Hớn Minh', 'duonghonminh@gmail.com', N'Thạc sĩ'
EXEC THEMGV N'Võ Kim Long', 'vokimlong@gmail.com', N'Cử nhân'
EXEC THEMGV N'Lê Quốc Bảo', 'lequocbao@gmail.com', N'Kỹ sư'
GO

-- Tao ma lop tu dong
CREATE FUNCTION TAOMALOP (@MACN VARCHAR(5))
RETURNS VARCHAR(8)
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM LOP WHERE MACN = @MACN)
		RETURN @MACN + '000'

	DECLARE @MALOPLONNHAT VARCHAR(8), @STT INT
	SET @MALOPLONNHAT = (SELECT TOP 1 MALOP FROM LOP WHERE MACN = @MACN ORDER BY MALOP DESC)
	SET @STT = CAST(RIGHT(@MALOPLONNHAT, 3) AS INT) + 1

	IF @STT < 10
		RETURN @MACN + '00' + CAST(@STT AS VARCHAR(1))
	ELSE IF @STT < 100
		RETURN @MACN + '0' + CAST(@STT AS VARCHAR(2))
	RETURN @MACN + CAST(@STT AS VARCHAR(3))
END
GO

CREATE PROCEDURE THEMLOP @MAGV VARCHAR(6), @MACN VARCHAR(5), @MANGANH VARCHAR(10), @TENLOP NVARCHAR(50), @SOLUONGSV INT
AS 
	DECLARE @MALOPTUDONG VARCHAR(8)
	SET @MALOPTUDONG = DBO.TAOMALOP(@MACN)
	INSERT INTO LOP VALUES (@MALOPTUDONG, @MAGV, @MACN, @MANGANH, @TENLOP, @SOLUONGSV)
GO

EXEC THEMLOP 'CN000', 'HV002', 'KHMT', N'Lớp Khoa học máy tính', 100
EXEC THEMLOP 'KS000', 'HV002', 'ATTT', N'Lớp An toàn thông tin', 50
EXEC THEMLOP 'THS000', 'HV002', 'KHMT', N'Lớp Khoa học máy tính', 90
EXEC THEMLOP 'TS000', 'HV001', 'ATTT', N'Lớp An toàn thông tin', 60
EXEC THEMLOP 'TS001', 'HV002', 'CNPM', N'Lớp Công nghệ phần mềm', 80
GO

-- Tao ma nganh tu dong
CREATE FUNCTION TAOMANGANH(@TENNGANH NVARCHAR(50))
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @I INT
	SET @I = 1

	DECLARE @KITU NVARCHAR(1), @MANGANH VARCHAR(10)
	SET @MANGANH = '' 
	WHILE @I <= LEN(@TENNGANH)
	BEGIN
		SET @KITU = SUBSTRING(@TENNGANH, @I, 1)
		IF @I = 1
			SET @MANGANH = @MANGANH + UPPER(@KITU) 
		ELSE IF @KITU = ' '
			SET @MANGANH = @MANGANH + UPPER(SUBSTRING(@TENNGANH, @I + 1, 1))
		SET @I = @I + 1
	END
	RETURN @MANGANH
END
GO

CREATE PROCEDURE THEMNGANH @TENNGANH NVARCHAR(50)
AS
	DECLARE @MANGANH VARCHAR(10)
	SET @MANGANH = DBO.TAOMANGANH(@TENNGANH)
	INSERT INTO NGANH VALUES (@MANGANH, @TENNGANH)
GO

EXEC THEMNGANH N'Khoa học máy tính'
EXEC THEMNGANH N'Công nghệ phần mềm'
EXEC THEMNGANH N'An toàn thông tin'
EXEC THEMNGANH N'Hệ thống quản lí thông tin'
GO

-- Tao trigger kiem tra rang buoc ma lop cua bang sinh vien
CREATE TRIGGER KTRAMALOP ON SINHVIEN 
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MALOP VARCHAR(8)
	SET @MALOP = (SELECT MALOP FROM INSERTED)
	IF NOT EXISTS (SELECT * FROM LOP WHERE MALOP = @MALOP)
	BEGIN
		PRINT(N'Mã lớp không tồn tại')
		ROLLBACK TRAN
	END
END

INSERT INTO SINHVIEN VALUES('SV001', 'HV001000', N'Võ Minh Khoa', '2004-03-11', N'Nam', 'TPHCM')
INSERT INTO SINHVIEN VALUES('SV002', 'HV001000', N'Võ Tấn Phát', '2004-09-2', N'Nam', N'Củ Chi')
INSERT INTO SINHVIEN VALUES('SV003', 'HV002002', N'Lương Bích Hữu', '2004-10-1', N'Nữ', N'Sa Đéc')
INSERT INTO SINHVIEN VALUES('SV004', 'HV002000', N'Triều Quang Vinh', '2004-11-2', N'Nam', N'Hà Nội')
INSERT INTO SINHVIEN VALUES('SV005', 'HV002001', N'Nguyễn Anh Thư', '2004-03-20', N'Nữ', N'Vĩnh Long')

ALTER TABLE SINHVIEN DROP CONSTRAINT FK_MALOP_SV_LOP

INSERT INTO SINHVIEN VALUES('SV006', 'HV001001', N'Nguyễn Minh Muôn', '2004-01-20', N'Nam', N'TPHCM')

UPDATE SINHVIEN 
SET MALOP = 'HV002005'
WHERE QUEQUAN = 'TPHCM'
GO

-- Tao Trigger kiem tra rang buoc mamon va magv cua bang khoa hoc
CREATE TRIGGER KTRAKHOAHOC ON KHOAHOC
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MAMON VARCHAR(5), @MAGV VARCHAR(5), @ERROR INT
	SELECT @ERROR = 0, @MAMON = MAMON, @MAGV = MAGV FROM INSERTED
	IF NOT EXISTS (SELECT * FROM MONHOC WHERE MAMON = @MAMON)
	BEGIN
		PRINT(N'Mã môn học không tồn tại')
		SET @ERROR = 1
	END
	
	IF NOT EXISTS (SELECT * FROM GIANGVIEN WHERE MAGV = @MAGV)
	BEGIN
		PRINT(N'Mã giảng viên không tồn tại')
		SET @ERROR = 1
	END

	IF @ERROR = 1
		ROLLBACK TRAN
END

ALTER TABLE KHOAHOC DROP CONSTRAINT FK_MAMON_KH_MH
ALTER TABLE KHOAHOC DROP CONSTRAINT FK_MAGV_KH_GV


INSERT INTO KHOAHOC VALUES ('MH001', 'KH001', 'TS001', '2-4-6')
INSERT INTO KHOAHOC VALUES ('MH001', 'KH002', 'TS001', '3-5-7')
INSERT INTO KHOAHOC VALUES ('MH001', 'KH003', 'TS002', '2-5-7')
INSERT INTO KHOAHOC VALUES ('MH002', 'KH001', 'TS003', '2-4-6')
INSERT INTO KHOAHOC VALUES ('MH002', 'KH002', 'CN000', '3-5-7')
INSERT INTO KHOAHOC VALUES ('MH002', 'KH003', 'KS000', '7-CN')

INSERT INTO KHOAHOC VALUES ('MH006', 'KH001', 'KS005', '3-5-7')

UPDATE KHOAHOC 
SET MAGV = 'TS006'
WHERE MAMON = 'MH002' AND MAKH = 'KH003'
GO

-- Tao Trigger kiem tra mien gia tri cua hoc vi trong bang giang vien
CREATE TRIGGER KTRAHOCVI ON GIANGVIEN
FOR INSERT, UPDATE
AS
	DECLARE @HOCVI NVARCHAR(20)
	SELECT @HOCVI = HOCVI FROM INSERTED 
	IF @HOCVI NOT IN (N'Thạc sĩ', N'Tiến sĩ', N'Cử nhân', N'Kỹ sư')
	BEGIN
		PRINT(N'Học vị không hợp lệ')
		ROLLBACK TRAN
	END

INSERT INTO GIANGVIEN VALUES ('CN001', N'Trần Vũ', 'tranvu@gmail.com', N'Cử nhân')
INSERT INTO GIANGVIEN VALUES ('KS001', N'Võ Thị Thu Hà', 'vothithuha@gmail.com', N'Kỹ sư')
INSERT INTO GIANGVIEN VALUES ('THS001', N'Trần Quang Khải', 'trangquangkhai@gmail.com', N'Thạc sĩ')

INSERT INTO GIANGVIEN VALUES ('GS000', N'Hồ Ngọc Hà', 'hongocha@gmail.com', N'Giáo sư')

Update GIANGVIEN
SET HOCVI = N'Phó giáo sư'
WHERE MAGV = 'THS000'
GO

-- Tao Trigger kiem tra mien gia tri tuoi cua sinh vien
CREATE TRIGGER KTRATUOI ON SINHVIEN
FOR INSERT, UPDATE
AS
	DECLARE @TUOI INT, @NAMSINH INT
	SELECT @NAMSINH = YEAR(NGAYSINH) FROM INSERTED 
	SET @TUOI = YEAR(GETDATE()) - @NAMSINH 
	IF @TUOI NOT BETWEEN 18 AND 35
	BEGIN
		PRINT(N'Số tuổi không hợp lệ')
		ROLLBACK TRAN
	END

INSERT INTO SINHVIEN VALUES('SV006', 'HV002001', N'Nguyễn Anh Khôi', '2006-03-20', N'Nam', N'Trà Vinh')

UPDATE SINHVIEN
SET NGAYSINH = '1985-10-1'
WHERE MASV = 'SV005'

